#if !defined(_WINAPI_WINNT_HPP_)
#define _WINAPI_WINNT_HPP_

namespace Core::WinAPI::WinNT {

FORWARD_POINTER(PRUNTIME_FUNCTION)
FORWARD_POINTER(PUNWIND_HISTORY_TABLE)

FORWARD_POINTER(PEXCEPTION_ROUTINE)
FORWARD_POINTER(PKNONVOLATILE_CONTEXT_POINTERS)
FORWARD_POINTER(PCONTEXT)

FORWARD_POINTER(LPTOP_LEVEL_EXCEPTION_FILTER)

FORWARD_POINTER(PEXCEPTION_RECORD)


//
//

NTSYSAPI PRUNTIME_FUNCTION NTAPI
RtlLookupFunctionEntry(DWORD64 ControlPc, PDWORD64 ImageBase, PUNWIND_HISTORY_TABLE HistoryTable);

NTSYSAPI VOID NTAPI RtlCaptureContext(PCONTEXT ContextRecord);

//
//

NTSYSAPI VOID NTAPI RtlUnwindEx(PVOID TargetFrame, PVOID TargetIp, PEXCEPTION_RECORD ExceptionRecord, PVOID ReturnValue,
                                PCONTEXT ContextRecord, PUNWIND_HISTORY_TABLE HistoryTable);

NTSYSAPI PEXCEPTION_ROUTINE NTAPI
RtlVirtualUnwind(DWORD HandlerType, DWORD64 ImageBase, DWORD64 ControlPc, PRUNTIME_FUNCTION FunctionEntry,
                 PCONTEXT ContextRecord, PVOID* HandlerData, PDWORD64 EstablisherFrame,
                 PKNONVOLATILE_CONTEXT_POINTERS ContextPointers);

}

#endif // _WINAPI_WINNT_HPP_

