#if !defined(_ERROR_CODE_HPP_)
#define _ERROR_CODE_HPP_

#include "BasicTypes.hpp"

enum class ErrorCode : DWORD {
    NO_ERROR = 0,
    ERROR_SUCCESS = 0,

    ERROR_INVALID_FUNCTION = 1,
    ERROR_FILE_NOT_FOUND = 2,
    ERROR_PATH_NOT_FOUND = 3,
    ERROR_TOO_MANY_OPEN_FILES = 4,
    ERROR_ACCESS_DENIED = 5,
    ERROR_INVALID_HANDLE = 6,
    ERROR_NOT_ENOUGH_MEMORY = 8,
    ERROR_NOT_READY = 15,
    ERROR_INVALID_PARAMETER = 87,
    ERROR_CALL_NOT_IMPLEMENTED = 120, // not implemented
    ERROR_MOD_NOT_FOUND = 126,
    ERROR_PROC_NOT_FOUND = 127,
    ERROR_INVALID_INDEX = 1413
};

#endif // _ERROR_CODE_HPP_

